variables:
  - &dockerfile Dockerfile
  - &repo codeberg.org/${CI_REPO_OWNER}/open-dronelog

when:
  branch: ${CI_REPO_DEFAULT_BRANCH}
  event: push

steps:
  publish:
    image: codeberg.org/woodpecker-plugins/docker-buildx:6.0.3
    settings:
      dockerfile: *dockerfile
      platforms: linux/amd64,linux/arm64
      repo: *repo
      registry: codeberg.org
      tags: latest
      username: ${CI_REPO_OWNER}
      password:
        from_secret: codeberg_token
      logins:
        - registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
          password:
            from_secret: docker_password
